apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: USERS_MICROSERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-backend-users-production-config-secret
                   key: USERS_MICROSERVICE_PORT
             - name: APP_API_PREFIX
               valueFrom:
                 secretKeyRef:
                   name: incta-backend-users-production-config-secret
                   key: APP_API_PREFIX
             - name: USERS_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-backend-users-production-config-secret
                   key: USERS_DATABASE_URL
